name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and publish to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven build
        run: ./mvnw package -Dnative

      - name: Build and publish to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: src/main/docker/Dockerfile.native
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/quarkus-servicebus/sample:latest