name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and publish to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up JBang
        uses: jbangdev/setup-jbang@main

      - name: Setup Quarkus
        run: |
          jbang trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          jbang app install --fresh --force quarkus@quarkusio

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Quarkus Build
        run: quarkus image build
